### ISSUE TITLE
Neurosity "device not connected"

### ISSUE THREAD

**Issue by Datagrdn** [neuromore/studio#115]
Neuromore recognizes my Neurosity Crown and displays real time raw EEG data in the top window in which it is listed as a "Neurosity Notion"

However, when I add the Notion node to my classifier I receive the "Device Not Connected" error. I can add the generic EEG Device node, which lists "Neurosity Notion" once live in the classifier. And it does produce signal, but only has one channel.

Is this a known bug or perhaps I missed a setup step?

Thanks for your help!

**Comment by Datagrdn** [comment]
I ended up using the EEG node with a "Select Channels" node to access each sensor on my device. Feel free to close this issue if there isn't another solution that I missed.

**Comment by cyberjunk** [comment]
@Datagrdn 
We support a multi-device setup for the "Neurosity Notion" node.
But this requires you to map the node(s) in the classifier to the connected device(s) by their IDs.
You can find the ID(s) of the connected device(s) in the Device Window (usually top-left window area).
Put the ID (+1) in the "Neurosity Notion" node attributes to map this node with this connected device.
