### ISSUE TITLE
MacOS installer 

### ISSUE THREAD

**Issue by nate2427** [neuromore/studio#130]
Having trouble with the MacOS installer on MacOS 12.2
![Screen Shot 2022-02-07 at 7 56 25 PM](https://user-images.githubusercontent.com/23044219/152897604-2b25d423-0c11-4fcb-abb9-397658278cf5.png)

Anyone know how to fix this issue?

**Comment by JuliusCosmoRomeo** [comment]
Hi Nate! Yes, you have to open your Security & Privacy settings of your operating system and allow the execution of neuromore Studio there.
