### ISSUE TITLE
How do I get it?

### ISSUE THREAD

**Issue by terabera** [neuromore/studio#15]
I wonder where to get the binary files.  There's nothing in the release folder.  And compiling resulted in a multitude of errors in Visual Studio 2019 Community Edition.  Right now the latest I seem to be able to obtain is the 1.4.2 version from the account dashboard at neuromore.com, which doesn't open properly on my PC with Windows 10 Enterprise.

Thanks!

**Comment by clifet** [comment]
> I wonder where to get the binary files. There's nothing in the release folder. And compiling resulted in a multitude of errors in Visual Studio 2019 Community Edition. Right now the latest I seem to be able to obtain is the 1.4.2 version from the account dashboard at neuromore.com, which doesn't open properly on my PC with Windows 10 Enterprise.
> 
> Thanks!

The instructions is in the README.md

https://github.com/neuromore/studio/blob/master/README.md

**Comment by terabera** [comment]
Thanks for your reply.  It says to go to the release folder, but upon doing so, I get to a page with no files.

**Comment by cyberjunk** [comment]
>> I wonder where to get the binary files. There's nothing in the release folder.

Github release binaries will be available very soon. We're just polishing up a few last things.

>> And compiling resulted in a multitude of errors in Visual Studio 2019 Community Edition

Would you please post the errors that you get with VS on Windows?
It's working fine with VS 2017 and 2019 over here, but we'll double check.

**Comment by terabera** [comment]
Great, thank you!  Unfortunately building takes an eternity and makes my computer unusable...also I had to set "tb.dd" or something similar to "Startup" in the list of projects...It was a mess.  Something might be wrong with my VS.  Anyway, I am looking forward to getting the binaries.  Thank you again!

**Comment by dioptre** [comment]
Hi guys, @cyberjunk uploaded the binaries which are now available @ https://github.com/neuromore/studio/releases
