### ISSUE TITLE
Neuromore doesn't detect Emotiv Epoc+ headset

### ISSUE THREAD

**Issue by Naowak** [neuromore/studio#19]
Hello everyone,

I tried to use Neuromore with the headset Emotiv Epoc+ but i never managed to connect it to the software, and I found nearly nothing online to help me out. Even the doc is quite short. The only information I found is :

"Emotiv EPOC / EPOC+

    Platforms: Windows
    Devices: EPOC, EPOC+ 

Plug in your dongle and turn on the device either before you start or while neuromore Studio is running. Connected devices will be detected automatically and shown in the interface."
https://doc.neuromore.com/?cat=0&page=2

The dongle is pluged, the headset is ON, but Neuromore never detects the device.

Do you have any advice ?
Thank you for your time.

**Comment by hilsbos** [comment]
Hi @Naowak,
to use emotive headsets with neuromore studio you need to get the source code and build your own version with emotiv support enabled.

Please follow this steps to do this:

1. Enable define INCLUDE_DEVICE_EMOTIV in Engine/Config.h
2. Provide matching emotiv sdk headers in /deps/include and the their prebuilt libs in /deps/prebuilt/win/x86 (and x64)
I'm afraid the second one might be not be that easy. 
The required version of the emotiv sdk is v3.0.0.41.

Please let us know if you have additional questions.
Patrick

**Comment by MrPiavushka** [comment]
hi @hilsbos  can you provide link for emotiv sdk v3.0.0.41.

**Comment by cyberjunk** [comment]
Hello @Naowak, Hello @MrPiavushka 

please see our devices [Wiki page](https://github.com/neuromore/studio/wiki/Devices), follow the steps in [section](https://github.com/neuromore/studio/wiki/Devices#emotiv-epocinsight) for the Emotiv Epoc. We recently upgraded our code so that it works with the [latest community SDK](https://github.com/Emotiv/community-sdk) of the vendor.

**Comment by cyberjunk** [comment]
Closing this. Seems answered. Please re-open if you have any more issues when using your EPOC+ device with the mentioned latest community SDK integrated in our Studio.
