### ISSUE TITLE
Community Forum/Chat 

### ISSUE THREAD

**Issue by stellarpower** [neuromore/studio#220]
Hi,

Would be good if Neuromore had a place for more general community discussion, as ideally Github is kept as cleanly as possible  to bugs and feature requests with the software. E.g. Discourse, Gitter, Talkyard; I have also seen some projects use Slack or Zulip chat.

Thanks!

**Comment by JuliusCosmoRomeo** [comment]
I see you already found the way to the Github Discussions. ;) Let's use that for communcty discussions. :)
