### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by DOBsby** [neuromore/studio#318]
I was just supposed to have a Zoom call a few minutes ago with one of the guys from Neuromore, but they never showed. Last version of the app was just about a year ago, which doesn't seem too old, and their Zendesk system still seems alive, but I haven't seen anyone from NM post here or reply to any emails, so... time to move on?

**Comment by hilsbos** [comment]
Hi @DOBsby,

Thank you for reaching out. We're still very much alive and already reached out to you to reschedule.
