### ISSUE TITLE
Executable version for Linux

### ISSUE THREAD

**Issue by VasudevDevulapally** [neuromore/studio#53]
Dear all,

I tried to download neuromore freeversion but i dont find any executable version to run on linux machine ( ubuntu 18.04) , kindly please let me know how to obtain a linux version.

Thanks
Vasudev

**Comment by cyberjunk** [comment]
You can find our binary releases [here](https://github.com/neuromore/studio/releases) on Github.
For Ubuntu 18.04 download the _Studio.deb_ (and see other instructions on that page).

**Comment by cyberjunk** [comment]
Closing this, seems answered.
