### ISSUE TITLE
Not able to create state machine in personal folder.

### ISSUE THREAD

**Issue by Rakesh420** [neuromore/studio#71]
I downloaded the latest version of neuromore studio and I am unable to create a state machine file in the personal folders.

**Comment by NibrasAz7** [comment]
I am facing the same issue.
Could you fix it?

**Comment by cyberjunk** [comment]
@Rakesh420 @NibrasAz7 

Sorry for the late reply.
We reviewed this issue and are happy to announce that it has been fixed:

Creating State-Machines and Experiences in the home-folder of a _Community_ User is now possible.
This was a _Professional_ feature so far, but we decided to make it accessible for our community.

**Comment by NibrasAz7** [comment]
Yes, I have tried immediately and it worked.
Thank you for your assistance

**Comment by arayes2000** [comment]
I am facing the same issue now, has this update been reversed?

**Comment by nibroosauro** [comment]
same here, I'm facing the same issue
