### ISSUE TITLE
unable to get data from OSC output nodes 

### ISSUE THREAD

**Issue by rpacz** [neuromore/studio#87]
Hello,
 I'm trying to get some data out of neuromore studio and into the outside. 
  When I use Mind Monitor for Muse (with port 7000) the OSC traffic is detected ok by different OSC monitors (the one that had the most information for me was Protokol).  Neuromore studio detects the incoming traffic at port 7000 as well.  However, when I try to use the OSC output node from inside neuromore studio, I can' detect that traffic with any OSC monitor.

I created a simple test classifier made up of a sine wave signal generator connected to an OSC output:
![test classifier](https://user-images.githubusercontent.com/75087989/101976144-470e1c00-3bf7-11eb-81b0-4e7f98d0d279.jpg)

My network settings are as follows (port: 4546) :

![network setup](https://user-images.githubusercontent.com/75087989/101976153-57be9200-3bf7-11eb-85e2-a33453790ed7.png)

And Protokol or any other OSC monitor comes up empty handed.
![OSC monitor](https://user-images.githubusercontent.com/75087989/101976252-45912380-3bf8-11eb-8e0a-154673cd5309.PNG)

I think that for some reason Neuromore studio blocks any external program from binding to the output port (in my case 4546 but any port I tried seemed to be blocked by the studio).

**Comment by rpacz** [comment]
I tested this with an OSC server written written in python and was able to see traffic ok.  I used the following code.

from pythonosc.dispatcher import Dispatcher
from pythonosc.osc_server import BlockingOSCUDPServer

def print_handler(address, *args):
    print(args[0])


def default_handler(address, *args):
    print(f"DEFAULT {address}: {args}")


dispatcher = Dispatcher()
dispatcher.map("/out/0*", print_handler)
dispatcher.set_default_handler(default_handler)

ip = "127.0.0.1"
port = 4546

server = BlockingOSCUDPServer((ip, port), dispatcher)
server.serve_forever()  # Blocks forever

**Comment by stellarpower** [comment]
When I run the above (and for my own similar code too), the port has already been bound to. It's not entirely clear to me how OSC output is meant to be working. Should Neuromore be connecting to an external server in order to provide it its output? In which case, how come it's binding to the port given in the settings? Or is it running its own server, that I should connect to, in which case, how would I go about receiving the callbacks for output values?

Thanks
