### ISSUE TITLE
Visualization on OSX

### ISSUE THREAD

**Issue by martahedl** [neuromore/studio#88]
Hi!
Thanks for this great software and the very compelling tutorials on https://www.neuromore.com/tutorials. However, when I was trying to do the visualization tutorial, I couldn't get neuromore to find the path of the visualization directory (i.e. the download folder "Studio-1.4.7"). I was wondering whether visualization is only possible on Windows (I noticed the .exe files), or am I missing something?
Thanks in advance,
Marlene.

**Comment by dioptre** [comment]
We publish the visualizations for windows only as part of the binary. Thanks!
