### ISSUE TITLE
An error occurs after few minutes of opening the application 

### ISSUE THREAD

**Issue by Sarthak031** [neuromore/studio#95]
@cyberjunk @dioptre  An Error occurs after few minutes of opening the application (Exception is thrown: read access violation. this was 0xFFFFFFFFFFFFFFFB.) and BLE devices start connecting with the system automatically.

**Comment by Sarthak031** [comment]
@cyberjunk @dioptre This Error occurs when the Bluetooth devices get connected automatically with the Windows Bluetooth. If we switch off the Bluetooth devices in the Neuromore application settings this error is solved automatically.

**Comment by Sarthak031** [comment]
@cyberjunk @dioptre Neuromore application, by default, is trying to connect nearby Bluetooth devices when we turn on the Bluetooth devices in the application setting. I have done some changes in the Neuromore application wherein I manually pair the Bluetooth device with the Windows Bluetooth manager and then I scan the available devices using the search option in the Devices panel on the top-left corner of the application window. Then the application is able to identify the device and offers to connect. This process seams to be much more reliable and consistent when it comes to Bluetooth devices.

**Comment by cyberjunk** [comment]
Hey @Sarthak031,

sorry for the late reply. Neuromore Studio (Version 1.4.9) only supports Heart-Rate-Monitors (HRM) on Bluetooth LE directly.
Unless you want to connect one of these devices, it's highly recommended to keep "Bluetooth" switched off in our settings.
This setting is NOT required for Bluetooth based EEG devices that are accessed by a vendor SDK or similar.
It may actually rather interfere with the communication of these devices...

**Comment by Sarthak031** [comment]
@cyberjunk Thank you for the confirmation.
